//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabyrinthGame.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GameResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GameResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LabyrinthGame.Resources.GameResources", typeof(GameResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The scoreboard is empty..
        /// </summary>
        internal static string EmptyScoreboardMessage {
            get {
                return ResourceManager.GetString("EmptyScoreboardMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your move (L=left, R=right, U=up, D=down): .
        /// </summary>
        internal static string EnterMoveMessage {
            get {
                return ResourceManager.GetString("EnterMoveMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congratulations! You escaped in.
        /// </summary>
        internal static string EscapedInXMovesMessage {
            get {
                return ResourceManager.GetString("EscapedInXMovesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good Bye!.
        /// </summary>
        internal static string GoodByeMessage {
            get {
                return ResourceManager.GetString("GoodByeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid move!.
        /// </summary>
        internal static string InvalidCommandMessage {
            get {
                return ResourceManager.GetString("InvalidCommandMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X .
        /// </summary>
        internal static string LabyrinthBlockedCellSign {
            get {
                return ResourceManager.GetString("LabyrinthBlockedCellSign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - .
        /// </summary>
        internal static string LabyrinthFreeCellSign {
            get {
                return ResourceManager.GetString("LabyrinthFreeCellSign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to moves.
        /// </summary>
        internal static string MovesMessage {
            get {
                return ResourceManager.GetString("MovesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * .
        /// </summary>
        internal static string PlayerPositionSign {
            get {
                return ResourceManager.GetString("PlayerPositionSign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your name for the top scoreboard:.
        /// </summary>
        internal static string RecordScoreMessage {
            get {
                return ResourceManager.GetString("RecordScoreMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scoreboard:.
        /// </summary>
        internal static string ScoreboardMessage {
            get {
                return ResourceManager.GetString("ScoreboardMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --&gt;.
        /// </summary>
        internal static string ScoreboardPrintDivider {
            get {
                return ResourceManager.GetString("ScoreboardPrintDivider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to “Labirinth” game. Please try to escape. Use &apos;top&apos; to view the top scoreboard, &apos;restart&apos; to start a new game and &apos;exit&apos; to quit the game..
        /// </summary>
        internal static string WelcomeMessage {
            get {
                return ResourceManager.GetString("WelcomeMessage", resourceCulture);
            }
        }
    }
}
